# Generated by Django 5.2.4 on 2025-07-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='annual_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_annual_price_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
