# Generated by Django 5.2.4 on 2025-08-04 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_enhance_brand_profile_comprehensive_branding'),
        ('subscription_billing', '0002_subscriptionplan_annual_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='includes_corporate_suite',
        ),
        migrations.AlterField(
            model_name='customer',
            name='tenant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_billing_customer_tenant', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_billing_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_billing_payment_transactions', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_billing_subscriptions', to='core.tenant'),
        ),
    ]
