# Generated by Django 5.2.4 on 2025-08-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_billing', '0003_remove_subscriptionplan_includes_corporate_suite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='additional_token_pack_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost of additional token pack', max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='additional_token_pack_size',
            field=models.IntegerField(default=0, help_text='Size of additional token packs'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='automation_workflow_limit',
            field=models.IntegerField(default=0, help_text='Number of active automation workflows allowed'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='includes_advanced_analytics',
            field=models.BooleanField(default=False, help_text='Access to advanced analytics and predictive insights'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='includes_budgeting',
            field=models.BooleanField(default=False, help_text='Access to budgeting and financial tools'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='includes_custom_integrations',
            field=models.BooleanField(default=False, help_text='Custom API development and integration support'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='includes_dedicated_support',
            field=models.BooleanField(default=False, help_text='Dedicated account manager and priority support'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='includes_design_studio',
            field=models.BooleanField(default=False, help_text='Access to full design studio features'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='includes_learning_center',
            field=models.BooleanField(default=False, help_text='Access to personalized learning paths'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='includes_project_management',
            field=models.BooleanField(default=False, help_text='Access to project management tools'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='includes_white_label',
            field=models.BooleanField(default=False, help_text='White-label solutions available'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='integration_limit',
            field=models.IntegerField(default=0, help_text='Number of social media integrations allowed'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='monthly_tokens',
            field=models.IntegerField(default=0, help_text='Number of tokens included per month'),
        ),
    ]
