# Generated by Django 5.2.4 on 2025-08-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_billing', '0004_subscriptionplan_additional_token_pack_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='client_portals_limit',
            field=models.IntegerField(default=0, help_text='Number of client portals allowed'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='includes_client_analytics',
            field=models.BooleanField(default=False, help_text='Access to client-specific analytics'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='includes_client_billing',
            field=models.BooleanField(default=False, help_text='Access to client billing and invoicing'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='includes_client_portals',
            field=models.BooleanField(default=False, help_text='Access to client portal management features'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='includes_client_support',
            field=models.BooleanField(default=False, help_text='Dedicated support for client portal management'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='includes_white_label_portals',
            field=models.BooleanField(default=False, help_text='White-label client portals with custom branding'),
        ),
    ]
