# Generated by Django 5.2.4 on 2025-08-13 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_billing', '0004_user_centric_subscriptions'),
        ('subscription_billing', '0005_subscriptionplan_client_portals_limit_and_more'),
    ]

    operations = [
    ]
