[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.11.1"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NPM_FLAGS = "--prefer-offline --no-audit"
  # Add build timeout and optimization flags
  NPM_CONFIG_CACHE = ".npm-cache"
  NPM_CONFIG_PREFER_OFFLINE = "true"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# API proxy redirects - more specific rules
[[redirects]]
  from = "/api/accounts/*"
  to = "https://digisol-backend.onrender.com/api/accounts/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/ai-services/*"
  to = "https://digisol-backend.onrender.com/api/ai-services/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/core/*"
  to = "https://digisol-backend.onrender.com/api/core/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/campaigns/*"
  to = "https://digisol-backend.onrender.com/api/campaigns/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/project-management/*"
  to = "https://digisol-backend.onrender.com/api/project-management/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/billing/*"
  to = "https://digisol-backend.onrender.com/api/billing/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/subscription-billing/*"
  to = "https://digisol-backend.onrender.com/api/subscription-billing/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/templates/*"
  to = "https://digisol-backend.onrender.com/api/templates/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/marketing-templates/*"
  to = "https://digisol-backend.onrender.com/api/marketing-templates/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/learning/*"
  to = "https://digisol-backend.onrender.com/api/learning/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/budgeting/*"
  to = "https://digisol-backend.onrender.com/api/budgeting/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/analytics/*"
  to = "https://digisol-backend.onrender.com/api/analytics/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/integrations/*"
  to = "https://digisol-backend.onrender.com/api/integrations/:splat"
  status = 200
  force = true

# Catch-all API redirect
[[redirects]]
  from = "/api/*"
  to = "https://digisol-backend.onrender.com/api/:splat"
  status = 200
  force = true

# SPA fallback - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# CORS headers for API routes
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 