# Generated by Django 5.2.4 on 2025-07-25 06:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_brandasset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Category name (e.g., 'Email Marketing', 'Social Media Ads')", max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Leave blank for global categories available to all tenants', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'Template Category',
                'verbose_name_plural': 'Template Categories',
                'ordering': ['name'],
                'unique_together': {('name', 'tenant')},
            },
        ),
        migrations.CreateModel(
            name='MarketingTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Template name (e.g., 'Welcome Series Email', 'Black Friday Facebook Ad')", max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('template_type', models.CharField(choices=[('email', 'Email'), ('social', 'Social Post'), ('ad_creative', 'Ad Creative'), ('landing_page', 'Landing Page'), ('blog_post', 'Blog Post'), ('other', 'Other')], default='other', help_text='Type of marketing asset', max_length=50)),
                ('content_json', models.JSONField(default=dict, help_text='Structured content (HTML for email, text for social, etc.)')),
                ('preview_image_url', models.URLField(blank=True, help_text='URL to a preview image of the template', max_length=500, null=True)),
                ('is_global', models.BooleanField(default=False, help_text='If True, available to all tenants (requires tenant=None)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Leave blank for global templates available to all tenants', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('category', models.ForeignKey(blank=True, help_text='Optional category for organizing templates', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='marketing_templates.templatecategory')),
            ],
            options={
                'verbose_name': 'Marketing Template',
                'verbose_name_plural': 'Marketing Templates',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'tenant')},
            },
        ),
    ]
