# Generated by Django 5.2.4 on 2025-08-04 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_auto_20250803_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integration',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='service_name',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='settings_json',
        ),
    ]
