# Generated by Django 5.2.4 on 2025-07-29 22:19
# Renamed from 0003 to 0002 after removing conflicting migrations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('email_sent', 'Email Sent'), ('email_opened', 'Email Opened'), ('email_clicked', 'Email Clicked'), ('social_post_viewed', 'Social Post Viewed'), ('social_post_clicked', 'Social Post Clicked'), ('lead_converted', 'Lead Converted'), ('conversion_event', 'Conversion Event'), ('campaign_sent', 'Campaign Sent'), ('form_submitted', 'Form Submitted'), ('unsubscribed', 'Unsubscribed'), ('sms_sent', 'SMS Sent'), ('sms_delivered', 'SMS Delivered'), ('sms_clicked', 'SMS Clicked')], max_length=50),
        ),
    ]
