# Generated by Django 5.2.4 on 2025-08-02 20:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_event_event_type'),
        ('campaigns', '0003_marketingcampaign_is_template'),
        ('core', '0017_contact_assigned_to_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadFunnelEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('MQL_Achieved', 'MQL Achieved'), ('SQL_Achieved', 'SQL Achieved'), ('Won_Opportunity', 'Won Opportunity'), ('Campaign_Touchpoint', 'Campaign Touchpoint'), ('Form_Submission', 'Form Submission'), ('Page_Visit', 'Page Visit'), ('Email_Opened', 'Email Opened'), ('Email_Clicked', 'Email Clicked')], max_length=100)),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.marketingcampaign')),
                ('campaign_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campaignstep')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnel_events', to='core.contact')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'Lead Funnel Event',
                'verbose_name_plural': 'Lead Funnel Events',
                'db_table': 'lead_funnel_events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tenant', 'event_type'], name='lead_funnel_tenant__ddd5ca_idx'), models.Index(fields=['contact', 'event_type'], name='lead_funnel_contact_d6d617_idx'), models.Index(fields=['campaign', 'event_type'], name='lead_funnel_campaig_5ad12b_idx'), models.Index(fields=['timestamp'], name='lead_funnel_timesta_831668_idx')],
            },
        ),
    ]
