# Generated by Django 5.2.4 on 2025-07-22 22:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_tenant_text_credits_tenant_text_credits_used'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Leave empty for global tutorials available to all tenants', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'Tutorial',
                'verbose_name_plural': 'Tutorials',
                'db_table': 'tutorials',
                'ordering': ['order', 'title'],
                'unique_together': {('title', 'tenant')},
            },
        ),
        migrations.CreateModel(
            name='TutorialSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='learning.tutorial')),
            ],
            options={
                'verbose_name': 'Tutorial Section',
                'verbose_name_plural': 'Tutorial Sections',
                'db_table': 'tutorial_sections',
                'ordering': ['order', 'title'],
                'unique_together': {('title', 'tutorial')},
            },
        ),
        migrations.CreateModel(
            name='TutorialStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('image', 'Image'), ('interactive', 'Interactive')], default='text', max_length=50)),
                ('content', models.TextField(help_text='Text/HTML content, or URL for video/image content')),
                ('order', models.IntegerField(default=0)),
                ('page_path', models.CharField(blank=True, help_text="Optional page path for deep linking (e.g., '/dashboard')", max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='learning.tutorialsection')),
            ],
            options={
                'verbose_name': 'Tutorial Step',
                'verbose_name_plural': 'Tutorial Steps',
                'db_table': 'tutorial_steps',
                'ordering': ['order', 'title'],
                'unique_together': {('title', 'section')},
            },
        ),
        migrations.CreateModel(
            name='UserTutorialProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_completed_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_by_users', to='learning.tutorialstep')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='learning.tutorial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Tutorial Progress',
                'verbose_name_plural': 'User Tutorial Progress',
                'db_table': 'user_tutorial_progress',
                'ordering': ['-started_at'],
                'unique_together': {('user', 'tutorial')},
            },
        ),
    ]
