# Generated by Django 5.2.4 on 2025-08-02 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignstep',
            name='false_path_next_step',
            field=models.ForeignKey(blank=True, help_text='Next step to execute when condition evaluates to False', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditional_false_parent', to='campaigns.campaignstep'),
        ),
        migrations.AddField(
            model_name='campaignstep',
            name='true_path_next_step',
            field=models.ForeignKey(blank=True, help_text='Next step to execute when condition evaluates to True', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditional_true_parent', to='campaigns.campaignstep'),
        ),
    ]
