# Generated by Django 5.2.4 on 2025-08-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaignstep_false_path_next_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingcampaign',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Indicates if this campaign record is meant to serve as a template'),
        ),
    ]
