# Generated by Django 5.2.4 on 2025-08-08 20:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_marketingcampaign_is_template'),
        ('core', '0020_agencyclientportal_agencyclientbilling_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignstep',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Campaign Step', 'verbose_name_plural': 'Campaign Steps'},
        ),
        migrations.AlterModelOptions(
            name='marketingcampaign',
            options={'ordering': ['-created_at'], 'verbose_name': 'Marketing Campaign', 'verbose_name_plural': 'Marketing Campaigns'},
        ),
        migrations.AddField(
            model_name='campaignstep',
            name='catalyst_optimized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaignstep',
            name='catalyst_suggestions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='campaignstep',
            name='content_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='campaignstep',
            name='execution_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaignstep',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campaignstep',
            name='last_executed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignstep',
            name='performance_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='audience_criteria',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='auto_optimization_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='campaign_type',
            field=models.CharField(choices=[('email', 'Email Campaign'), ('social', 'Social Media Campaign'), ('paid_ads', 'Paid Advertising'), ('content', 'Content Marketing'), ('event', 'Event Marketing'), ('product_launch', 'Product Launch'), ('lead_nurturing', 'Lead Nurturing'), ('retention', 'Customer Retention'), ('multi_channel', 'Multi-Channel')], default='email', max_length=50),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='catalyst_health_score',
            field=models.IntegerField(blank=True, help_text='AI-generated health score (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='catalyst_recommendations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='conversion_goals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='estimated_reach',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='last_optimized',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='performance_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='spent_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='target_roi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='template_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='campaignstep',
            name='false_path_next_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditional_false_parent', to='campaigns.campaignstep'),
        ),
        migrations.AlterField(
            model_name='campaignstep',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='campaignstep',
            name='step_type',
            field=models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS'), ('Ad', 'Ad Display'), ('Conditional', 'Conditional Logic'), ('Delay', 'Delay'), ('Goal', 'Campaign Goal'), ('AI_Insight', 'AI Insight/Action'), ('Trigger', 'Trigger'), ('Social_Post', 'Social Media Post'), ('Landing_Page', 'Landing Page'), ('Webhook', 'Webhook'), ('A_B_Test', 'A/B Test')], max_length=50),
        ),
        migrations.AlterField(
            model_name='campaignstep',
            name='true_path_next_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditional_true_parent', to='campaigns.campaignstep'),
        ),
        migrations.AlterField(
            model_name='marketingcampaign',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='marketingcampaign',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='marketingcampaign',
            name='objective',
            field=models.CharField(choices=[('awareness', 'Brand Awareness'), ('traffic', 'Drive Traffic'), ('leads', 'Generate Leads'), ('sales', 'Increase Sales'), ('engagement', 'Boost Engagement'), ('conversion', 'Improve Conversion'), ('retention', 'Customer Retention'), ('loyalty', 'Build Loyalty')], default='leads', max_length=50),
        ),
        migrations.CreateModel(
            name='CampaignAudience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('segment_type', models.CharField(choices=[('static', 'Static List'), ('dynamic', 'Dynamic Segment'), ('lookalike', 'Lookalike Audience'), ('custom', 'Custom Criteria')], default='static', max_length=20)),
                ('criteria', models.JSONField(blank=True, default=dict)),
                ('filters', models.JSONField(blank=True, default=list)),
                ('estimated_size', models.IntegerField(blank=True, null=True)),
                ('actual_size', models.IntegerField(blank=True, null=True)),
                ('engagement_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('conversion_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('catalyst_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('catalyst_recommendations', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'Campaign Audience',
                'verbose_name_plural': 'Campaign Audiences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('email_series', 'Email Series'), ('social_campaign', 'Social Media Campaign'), ('product_launch', 'Product Launch'), ('holiday_promotion', 'Holiday Promotion'), ('lead_nurturing', 'Lead Nurturing'), ('customer_onboarding', 'Customer Onboarding'), ('re_engagement', 'Re-engagement'), ('seasonal', 'Seasonal Campaign')], max_length=50)),
                ('campaign_data', models.JSONField(default=dict)),
                ('steps_data', models.JSONField(default=list)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('usage_count', models.IntegerField(default=0)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'Campaign Template',
                'verbose_name_plural': 'Campaign Templates',
                'ordering': ['-usage_count', '-rating'],
            },
        ),
        migrations.CreateModel(
            name='CatalystInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('performance_alert', 'Performance Alert'), ('optimization_suggestion', 'Optimization Suggestion'), ('anomaly_detection', 'Anomaly Detection'), ('trend_forecast', 'Trend Forecast'), ('audience_insight', 'Audience Insight'), ('content_recommendation', 'Content Recommendation'), ('timing_optimization', 'Timing Optimization'), ('budget_recommendation', 'Budget Recommendation'), ('competitive_analysis', 'Competitive Analysis')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('recommendation', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('predicted_impact', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_actioned', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('action_taken', models.TextField(blank=True)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalyst_insights', to='campaigns.marketingcampaign')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalyst_insights', to='campaigns.campaignstep')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'Catalyst Insight',
                'verbose_name_plural': 'Catalyst Insights',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hour', models.IntegerField(blank=True, null=True)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('opens', models.IntegerField(default=0)),
                ('bounces', models.IntegerField(default=0)),
                ('unsubscribes', models.IntegerField(default=0)),
                ('ctr', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('cpc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cpm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('conversion_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('roi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_data', to='campaigns.marketingcampaign')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_data', to='campaigns.campaignstep')),
            ],
            options={
                'verbose_name': 'Campaign Performance',
                'verbose_name_plural': 'Campaign Performance Data',
                'ordering': ['-date', '-hour'],
                'unique_together': {('campaign', 'step', 'date', 'hour')},
            },
        ),
    ]
