# Generated by Django

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_remove_tenant_and_rename_catalyst'),
    ]

    operations = [
        # Drop all existing tables and recreate them
        migrations.RunSQL(
            # Drop all campaign-related tables (SQLite compatible)
            """
            DROP TABLE IF EXISTS campaigns_campaignaudience;
            DROP TABLE IF EXISTS campaigns_campaignperformance;
            DROP TABLE IF EXISTS campaigns_optimizerinsight;
            DROP TABLE IF EXISTS campaigns_campaignstep;
            DROP TABLE IF EXISTS campaigns_campaigntemplate;
            DROP TABLE IF EXISTS campaigns_marketingcampaign;
            """,
            # Reverse SQL (empty since we're dropping everything)
            ""
        ),
        # Recreate tables with the correct schema
        migrations.RunSQL(
            # Create MarketingCampaign table with correct fields (SQLite compatible)
            """
            CREATE TABLE campaigns_marketingcampaign (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name VARCHAR(255) NOT NULL,
                description TEXT,
                campaign_type VARCHAR(50),
                objective VARCHAR(50),
                status VARCHAR(50) DEFAULT 'Draft',
                start_date DATE,
                end_date DATE,
                target_audience_segment TEXT,
                audience_criteria TEXT,
                estimated_reach INTEGER,
                budget DECIMAL(10,2),
                target_roi DECIMAL(5,2),
                auto_optimization_enabled BOOLEAN DEFAULT 0,
                is_template BOOLEAN DEFAULT 0,
                template_category VARCHAR(100),
                conversion_goals TEXT,
                optimizer_health_score INTEGER,
                optimizer_optimized BOOLEAN DEFAULT 0,
                optimizer_recommendations TEXT,
                optimizer_suggestions TEXT,
                actual_spent DECIMAL(10,2) DEFAULT 0,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
            );
            """,
            # Reverse SQL
            "DROP TABLE IF EXISTS campaigns_marketingcampaign;"
        ),
        migrations.RunSQL(
            # Create CampaignStep table
            """
            CREATE TABLE campaigns_campaignstep (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                campaign_id INTEGER REFERENCES campaigns_marketingcampaign(id),
                step_type VARCHAR(50),
                name VARCHAR(255),
                description TEXT,
                order_index INTEGER DEFAULT 0,
                config TEXT,
                content_data TEXT,
                metadata TEXT,
                is_enabled BOOLEAN DEFAULT 1,
                execution_count INTEGER DEFAULT 0,
                last_executed DATETIME,
                optimizer_optimized BOOLEAN DEFAULT 0,
                optimizer_suggestions TEXT,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
            );
            """,
            "DROP TABLE IF EXISTS campaigns_campaignstep;"
        ),
        migrations.RunSQL(
            # Create OptimizerInsight table
            """
            CREATE TABLE campaigns_optimizerinsight (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                campaign_id INTEGER REFERENCES campaigns_marketingcampaign(id),
                insight_type VARCHAR(50),
                title VARCHAR(255),
                description TEXT,
                recommendation TEXT,
                priority VARCHAR(20) DEFAULT 'medium',
                confidence_score DECIMAL(5,2),
                context_data TEXT,
                is_dismissed BOOLEAN DEFAULT 0,
                is_actioned BOOLEAN DEFAULT 0,
                action_taken TEXT,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
            );
            """,
            "DROP TABLE IF EXISTS campaigns_optimizerinsight;"
        ),
        migrations.RunSQL(
            # Create CampaignPerformance table
            """
            CREATE TABLE campaigns_campaignperformance (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                campaign_id INTEGER REFERENCES campaigns_marketingcampaign(id),
                date DATE,
                impressions INTEGER DEFAULT 0,
                clicks INTEGER DEFAULT 0,
                conversions INTEGER DEFAULT 0,
                revenue DECIMAL(10,2) DEFAULT 0,
                cost DECIMAL(10,2) DEFAULT 0,
                roi DECIMAL(5,2),
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
            );
            """,
            "DROP TABLE IF EXISTS campaigns_campaignperformance;"
        ),
        migrations.RunSQL(
            # Create CampaignAudience table
            """
            CREATE TABLE campaigns_campaignaudience (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                campaign_id INTEGER REFERENCES campaigns_marketingcampaign(id),
                audience_name VARCHAR(255),
                audience_criteria TEXT,
                size INTEGER,
                engagement_rate DECIMAL(5,2),
                conversion_rate DECIMAL(5,2),
                optimizer_score DECIMAL(5,2),
                optimizer_recommendations TEXT,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
            );
            """,
            "DROP TABLE IF EXISTS campaigns_campaignaudience;"
        ),
        migrations.RunSQL(
            # Create CampaignTemplate table
            """
            CREATE TABLE campaigns_campaigntemplate (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name VARCHAR(255),
                description TEXT,
                category VARCHAR(100),
                campaign_data TEXT,
                steps_data TEXT,
                usage_count INTEGER DEFAULT 0,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
            );
            """,
            "DROP TABLE IF EXISTS campaigns_campaigntemplate;"
        ),
    ]
