# Generated by Django 5.2.4 on 2025-07-20 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_brandprofile_campaign_automationworkflow_contact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentGenerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField()),
                ('content_type', models.CharField(choices=[('email_subject', 'Email Subject'), ('email_body', 'Email Body'), ('social_post', 'Social Media Post'), ('blog_title', 'Blog Title'), ('blog_content', 'Blog Content'), ('ad_copy', 'Advertisement Copy'), ('landing_page', 'Landing Page Content'), ('product_description', 'Product Description')], max_length=50)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('generated_content', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('credits_used', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'Content Generation Request',
                'verbose_name_plural': 'Content Generation Requests',
                'db_table': 'content_generation_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
