# Generated by Django 5.2.4 on 2025-07-22 21:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0002_imagegenerationrequest'),
        ('core', '0004_tenant_text_credits_tenant_text_credits_used'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('campaign_optimization', 'Campaign Optimization'), ('lead_nurturing', 'Lead Nurturing'), ('churn_prediction', 'Churn Prediction'), ('content_strategy', 'Content Strategy'), ('audience_targeting', 'Audience Targeting'), ('budget_allocation', 'Budget Allocation'), ('performance_improvement', 'Performance Improvement')], max_length=100)),
                ('recommendation_text', models.TextField()),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('is_actionable', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('is_actioned', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Recommendation',
                'verbose_name_plural': 'AI Recommendations',
                'db_table': 'ai_recommendations',
                'ordering': ['-created_at'],
            },
        ),
    ]
