# Generated by Django 5.2.4 on 2025-07-23 07:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0003_airecommendation'),
        ('core', '0009_rename_automation__tenant__workflo_idx_automation__tenant__8e2335_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('personality_description', models.TextField(blank=True)),
                ('specialization', models.CharField(choices=[('marketing_strategy', 'Marketing Strategy'), ('budget_analysis', 'Budget Analysis'), ('content_creation', 'Content Creation'), ('campaign_optimization', 'Campaign Optimization'), ('lead_nurturing', 'Lead Nurturing'), ('general_orchestration', 'General Orchestration')], default='general_orchestration', max_length=100)),
                ('api_model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Leave empty for global AI agents available to all tenants', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'AI Profile',
                'verbose_name_plural': 'AI Profiles',
                'db_table': 'ai_profiles',
                'ordering': ['specialization', 'name'],
                'unique_together': {('name', 'tenant')},
            },
        ),
        migrations.AddField(
            model_name='airecommendation',
            name='generated_by_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_recommendations', to='ai_services.aiprofile'),
        ),
        migrations.CreateModel(
            name='AITask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('objective', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('delegated', 'Delegated')], default='pending', max_length=50)),
                ('context_data', models.JSONField(default=dict)),
                ('result_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='ai_services.aiprofile')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_tasks', to='ai_services.aitask')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_ai_tasks', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'AI Task',
                'verbose_name_plural': 'AI Tasks',
                'db_table': 'ai_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIInteractionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('ai_agent', 'AI Agent'), ('system', 'System')], max_length=50)),
                ('message_content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ai_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_services.aiprofile')),
                ('ai_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_services.aitask')),
            ],
            options={
                'verbose_name': 'AI Interaction Log',
                'verbose_name_plural': 'AI Interaction Logs',
                'db_table': 'ai_interaction_logs',
                'ordering': ['timestamp'],
            },
        ),
    ]
