# Generated by Django 5.2.4 on 2025-07-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0004_aiprofile_airecommendation_generated_by_agent_aitask_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagegenerationrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Image Generation Request', 'verbose_name_plural': 'Image Generation Requests'},
        ),
        migrations.AddField(
            model_name='imagegenerationrequest',
            name='edited_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='imagegenerationrequest',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='imagegenerationrequest',
            table='image_generation_requests',
        ),
    ]
