# Generated by Django 5.2.4 on 2025-07-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0005_alter_imagegenerationrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprofile',
            name='specialization',
            field=models.CharField(choices=[('marketing_strategy', 'Marketing Strategy'), ('budget_analysis', 'Budget Analysis'), ('content_creation', 'Content Creation'), ('campaign_optimization', 'Campaign Optimization'), ('lead_nurturing', 'Lead Nurturing'), ('general_orchestration', 'General Orchestration'), ('data_analysis', 'Data Analysis'), ('hr_management', 'HR Management'), ('integrations_management', 'Integrations Management'), ('learning_guidance', 'Learning Guidance')], default='general_orchestration', max_length=100),
        ),
    ]
