# Generated by Django 5.2.4 on 2025-07-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0008_alter_aiprofile_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegenerationrequest',
            name='design_parameters',
            field=models.JSONField(blank=True, default=dict, help_text='Stores specific parameters for the chosen design_type'),
        ),
        migrations.AddField(
            model_name='imagegenerationrequest',
            name='design_type',
            field=models.CharField(choices=[('general', 'General Image'), ('logo', 'Logo'), ('ad_banner', 'Ad Banner'), ('social_post', 'Social Media Post'), ('business_card', 'Business Card'), ('flyer', 'Flyer'), ('presentation_slide', 'Presentation Slide')], default='general', help_text='Specifies the intended output type for the design', max_length=50),
        ),
    ]
