# Generated by Django 5.2.4 on 2025-07-29 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0009_imagegenerationrequest_design_parameters_and_more'),
        ('core', '0013_remove_brandprofile_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airecommendation',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Campaign this recommendation is for (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='core.campaign'),
        ),
    ]
