# Generated by Django 5.2.4 on 2025-08-03 03:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0010_add_campaign_field_to_ai_recommendation'),
        ('core', '0018_enhance_brand_profile_comprehensive_branding'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIEcosystemHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_score', models.IntegerField(help_text='Overall health score (0-100)')),
                ('active_agents', models.IntegerField()),
                ('total_agents', models.IntegerField()),
                ('system_status', models.CharField(choices=[('optimal', 'Optimal'), ('good', 'Good'), ('attention', 'Needs Attention'), ('critical', 'Critical')], max_length=20)),
                ('agent_statuses', models.JSONField(default=list, help_text='Detailed status of each agent')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'AI Ecosystem Health',
                'verbose_name_plural': 'AI Ecosystem Health',
                'db_table': 'ai_ecosystem_health',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='StructuraInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('prediction', 'Prediction'), ('recommendation', 'Recommendation'), ('alert', 'Alert'), ('opportunity', 'Opportunity')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('confidence', models.IntegerField(help_text='Confidence score (0-100)')),
                ('impact', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('category', models.CharField(help_text='Business category (e.g., engagement, budget, retention)', max_length=100)),
                ('actionable', models.BooleanField(default=True)),
                ('action_text', models.CharField(blank=True, max_length=100, null=True)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_insights', to='ai_services.aiprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'Structura Insight',
                'verbose_name_plural': 'Structura Insights',
                'db_table': 'structura_insights',
                'ordering': ['-created_at'],
            },
        ),
    ]
