# Generated by Django 5.2.4 on 2025-07-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_brandprofile_campaign_automationworkflow_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='image_credits',
            field=models.IntegerField(default=100),
        ),
    ]
