# Generated by Django 5.2.4 on 2025-07-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tenant_image_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='text_credits',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='tenant',
            name='text_credits_used',
            field=models.IntegerField(default=0),
        ),
    ]
