# Generated by Django 5.2.4 on 2025-07-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tenant_text_credits_tenant_text_credits_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='planning_credits',
            field=models.IntegerField(default=50),
        ),
    ]
