# Generated by Django 5.2.4 on 2025-07-23 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tenant_planning_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandprofile',
            name='logo_url',
            field=models.ImageField(blank=True, null=True, upload_to='brand_logos/'),
        ),
    ]
