# Generated by Django 5.2.4 on 2025-07-23 07:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_automationexecution'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='automationexecution',
            new_name='automation__tenant__8e2335_idx',
            old_name='automation__tenant__workflo_idx',
        ),
        migrations.RenameIndex(
            model_name='automationexecution',
            new_name='automation__contact_1c6a93_idx',
            old_name='automation__contact_status_idx',
        ),
        migrations.RenameIndex(
            model_name='automationexecution',
            new_name='automation__last_ex_aadb02_idx',
            old_name='automation__last_exe_idx',
        ),
        migrations.AlterField(
            model_name='automationexecution',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
