# Generated by Django 5.2.4 on 2025-07-23 08:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0005_alter_imagegenerationrequest_options_and_more'),
        ('core', '0009_rename_automation__tenant__workflo_idx_automation__tenant__8e2335_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('image', 'Image'), ('logo', 'Logo'), ('document', 'Document'), ('other', 'Other')], default='image', max_length=50)),
                ('file_url', models.URLField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_shared_with_clients', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('original_image_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_assets', to='ai_services.imagegenerationrequest')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'Brand Asset',
                'verbose_name_plural': 'Brand Assets',
                'db_table': 'brand_assets',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'tenant')},
            },
        ),
    ]
