# Generated by Django 5.2.4 on 2025-07-27 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_subscription_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='image_credits',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='planning_credits',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='text_credits',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='text_credits_used',
        ),
    ]
