# Generated by Django 5.2.4 on 2025-07-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_tenant_image_credits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandprofile',
            name='accent_color',
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='brand_values',
            field=models.JSONField(blank=True, default=list, help_text="List of brand's core values"),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='brand_voice',
            field=models.TextField(blank=True, help_text="Brand's tone of voice and personality", null=True),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='competitors',
            field=models.JSONField(blank=True, default=list, help_text='List of key competitors'),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Primary contact email', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='description',
            field=models.TextField(blank=True, help_text='Brand description', null=True),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='industry',
            field=models.CharField(blank=True, help_text='Industry the brand operates in', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='key_messaging',
            field=models.JSONField(blank=True, default=list, help_text='List of core messages or slogans'),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='mission',
            field=models.TextField(blank=True, help_text="Brand's mission statement", null=True),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='name',
            field=models.CharField(blank=True, help_text='Brand name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='secondary_color',
            field=models.CharField(default='#ffffff', help_text='Secondary brand color (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='social_media_links',
            field=models.JSONField(blank=True, default=dict, help_text='Dictionary of social media URLs'),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='target_audience',
            field=models.CharField(blank=True, help_text='Primary target audience', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='target_audience_description',
            field=models.TextField(blank=True, help_text='Detailed description of ideal customer', null=True),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='vision',
            field=models.TextField(blank=True, help_text="Brand's vision statement", null=True),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='website_url',
            field=models.URLField(blank=True, help_text="Brand's website URL", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='font_family',
            field=models.CharField(default='Arial, sans-serif', help_text='Primary font family', max_length=100),
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='primary_color',
            field=models.CharField(default='#000000', help_text='Primary brand color (hex)', max_length=7),
        ),
    ]
