# Generated by Django 5.2.4 on 2025-07-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_brandprofile_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_activity_summary',
            field=models.TextField(blank=True, help_text='AI-generated summary of recent interactions', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_contact_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='lead_source',
            field=models.CharField(blank=True, help_text='e.g., Website, Referral, Cold Call', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='lead_status',
            field=models.CharField(default='New Lead', help_text='e.g., New Lead, Contacted, Qualified, Unqualified, Customer', max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='next_action_suggestion',
            field=models.TextField(blank=True, help_text='AI-generated suggestion for the next best action', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='priority',
            field=models.CharField(default='Medium', help_text='e.g., High, Medium, Low', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='score',
            field=models.IntegerField(default=0, help_text='A numerical lead score'),
        ),
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='For custom categorization'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
