# Generated by Django 5.2.4 on 2025-07-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_contact_job_title_contact_last_activity_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='suggested_persona',
            field=models.CharField(blank=True, help_text="AI-suggested buyer persona name (e.g., 'Tech Innovator', 'SMB Owner', 'Enterprise Buyer')", max_length=255, null=True),
        ),
    ]
