# Generated by Django 5.2.4 on 2025-08-03 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_contact_assigned_to_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brandprofile',
            name='app_icon_url',
            field=models.ImageField(blank=True, help_text='App icon for mobile/tablet', null=True, upload_to='brand_assets/'),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='background_color',
            field=models.CharField(default='#FFFFFF', help_text='Main background color (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='base_font_size',
            field=models.IntegerField(default=16, help_text='Base font size in pixels'),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='branding_status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('not_configured', 'Not Configured')], default='not_configured', help_text='Current status of branding configuration', max_length=20),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='button_primary_bg',
            field=models.CharField(default='#1F4287', help_text='Primary button background color', max_length=7),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='button_primary_border_radius',
            field=models.IntegerField(default=8, help_text='Primary button border radius in pixels'),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='button_primary_hover_bg',
            field=models.CharField(default='#1A365D', help_text='Primary button hover background color', max_length=7),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='button_primary_text',
            field=models.CharField(default='#FFFFFF', help_text='Primary button text color', max_length=7),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='button_secondary_bg',
            field=models.CharField(default='#E2E8F0', help_text='Secondary button background color', max_length=7),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='button_secondary_border_radius',
            field=models.IntegerField(default=8, help_text='Secondary button border radius in pixels'),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='button_secondary_text',
            field=models.CharField(default='#1A202C', help_text='Secondary button text color', max_length=7),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='custom_css',
            field=models.TextField(blank=True, help_text='Custom CSS code', null=True),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='custom_css_enabled',
            field=models.BooleanField(default=False, help_text='Whether custom CSS is enabled'),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='custom_js',
            field=models.TextField(blank=True, help_text='Custom JavaScript code', null=True),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='custom_js_enabled',
            field=models.BooleanField(default=False, help_text='Whether custom JavaScript is enabled'),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='dark_mode_logo_url',
            field=models.ImageField(blank=True, help_text='Dark mode logo', null=True, upload_to='brand_logos/'),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='email_footer_text',
            field=models.TextField(blank=True, help_text='Email template footer text', null=True),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='email_header_logo',
            field=models.ImageField(blank=True, help_text='Email template header logo', null=True, upload_to='brand_assets/'),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='email_primary_color',
            field=models.CharField(default='#1F4287', help_text='Email template primary color', max_length=7),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='favicon_url',
            field=models.ImageField(blank=True, help_text='Favicon', null=True, upload_to='brand_assets/'),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='font_weights',
            field=models.JSONField(blank=True, default=list, help_text="List of font weights (e.g., ['400', '500', '600'])"),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='headings_font_family',
            field=models.CharField(default='Inter', help_text='Headings font family', max_length=100),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='input_bg_color',
            field=models.CharField(default='#FFFFFF', help_text='Input field background color', max_length=7),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='input_border_color',
            field=models.CharField(default='#E2E8F0', help_text='Input field border color', max_length=7),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='input_border_radius',
            field=models.IntegerField(default=8, help_text='Input field border radius in pixels'),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='input_focus_color',
            field=models.CharField(default='#1F4287', help_text='Input field focus color', max_length=7),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='landing_page_bg_image',
            field=models.ImageField(blank=True, help_text='Landing page background image', null=True, upload_to='brand_assets/'),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='landing_page_footer_text',
            field=models.TextField(blank=True, help_text='Landing page footer text', null=True),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='landing_page_overlay_color',
            field=models.CharField(default='#000000', help_text='Landing page overlay color', max_length=7),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='landing_page_overlay_opacity',
            field=models.FloatField(default=0.5, help_text='Landing page overlay opacity (0.0 to 1.0)'),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='landing_page_welcome_message',
            field=models.TextField(blank=True, help_text='Landing page welcome message', null=True),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_profiles_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='link_color',
            field=models.CharField(default='#3182CE', help_text='Link color (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='nav_bar_active_color',
            field=models.CharField(default='#1F4287', help_text='Navigation bar active item color', max_length=7),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='nav_bar_bg_color',
            field=models.CharField(default='#FFFFFF', help_text='Navigation bar background color', max_length=7),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='nav_bar_text_color',
            field=models.CharField(default='#1A202C', help_text='Navigation bar text color', max_length=7),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='primary_text_color',
            field=models.CharField(default='#1A202C', help_text='Primary text color (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='scrollbar_thumb_color',
            field=models.CharField(default='#CBD5E0', help_text='Scrollbar thumb color', max_length=7),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='scrollbar_track_color',
            field=models.CharField(default='#F7FAFC', help_text='Scrollbar track color', max_length=7),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='secondary_text_color',
            field=models.CharField(default='#718096', help_text='Secondary text color (hex)', max_length=7),
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='font_family',
            field=models.CharField(default='Inter', help_text='Primary font family', max_length=100),
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='logo_url',
            field=models.ImageField(blank=True, help_text='Main logo', null=True, upload_to='brand_logos/'),
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='primary_color',
            field=models.CharField(default='#1F4287', help_text='Primary brand color (hex)', max_length=7),
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='secondary_color',
            field=models.CharField(default='#FFC300', help_text='Secondary brand color (hex)', max_length=7),
        ),
    ]
