# Generated by Django 5.2.4 on 2025-08-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_enhance_brand_profile_comprehensive_branding'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='tokens_purchased_additional',
            field=models.IntegerField(default=0, help_text='Additional tokens purchased beyond plan allocation'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tokens_used_current_period',
            field=models.IntegerField(default=0, help_text='Tokens used in the current billing period'),
        ),
    ]
