# Generated by Django 5.2.4 on 2025-08-05 19:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_tenant_tokens_purchased_additional_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyClientPortal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('client_company', models.CharField(blank=True, max_length=255, null=True)),
                ('client_website', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('access_level', models.CharField(choices=[('basic', 'Basic Access'), ('standard', 'Standard Access'), ('premium', 'Premium Access'), ('enterprise', 'Enterprise Access')], default='standard', max_length=20)),
                ('custom_branding', models.BooleanField(default=False)),
                ('custom_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('portal_theme', models.JSONField(blank=True, default=dict)),
                ('features_enabled', models.JSONField(blank=True, default=dict, help_text='Dictionary of enabled features')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('custom', 'Custom')], default='monthly', max_length=20)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('setup_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('contacts_limit', models.IntegerField(default=1000)),
                ('contacts_used', models.IntegerField(default=0)),
                ('campaigns_limit', models.IntegerField(default=10)),
                ('campaigns_used', models.IntegerField(default=0)),
                ('automations_limit', models.IntegerField(default=5)),
                ('automations_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_client_portals', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Agency Client Portal',
                'verbose_name_plural': 'Agency Client Portals',
                'db_table': 'agency_client_portals',
                'unique_together': {('client_email', 'parent_tenant')},
            },
        ),
        migrations.CreateModel(
            name='AgencyClientBilling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('overage_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('setup_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='core.agencyclientportal')),
            ],
            options={
                'verbose_name': 'Agency Client Billing',
                'verbose_name_plural': 'Agency Client Billing',
                'db_table': 'agency_client_billing',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgencyClientUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('viewer', 'Viewer'), ('editor', 'Editor')], default='viewer', max_length=20)),
                ('can_view_analytics', models.BooleanField(default=True)),
                ('can_manage_campaigns', models.BooleanField(default=False)),
                ('can_manage_contacts', models.BooleanField(default=False)),
                ('can_manage_automations', models.BooleanField(default=False)),
                ('can_export_data', models.BooleanField(default=False)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('password_reset_token', models.CharField(blank=True, max_length=255, null=True)),
                ('password_reset_expires', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_users', to='core.agencyclientportal')),
            ],
            options={
                'verbose_name': 'Agency Client User',
                'verbose_name_plural': 'Agency Client Users',
                'db_table': 'agency_client_users',
            },
        ),
        migrations.CreateModel(
            name='AgencyClientActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('login', 'User Login'), ('campaign_created', 'Campaign Created'), ('campaign_updated', 'Campaign Updated'), ('contact_added', 'Contact Added'), ('automation_created', 'Automation Created'), ('report_generated', 'Report Generated'), ('data_exported', 'Data Exported'), ('settings_updated', 'Settings Updated'), ('billing_updated', 'Billing Updated'), ('support_requested', 'Support Requested')], max_length=50)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.agencyclientportal')),
                ('client_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.agencyclientuser')),
            ],
            options={
                'verbose_name': 'Agency Client Activity',
                'verbose_name_plural': 'Agency Client Activities',
                'db_table': 'agency_client_activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
